# Generated by Django 2.1.1 on 2018-10-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descricao',
            new_name='nome',
        ),
    ]
