# Generated by Django 2.1.1 on 2018-10-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0002_auto_20181016_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='descricao',
        ),
    ]
