# Generated by Django 2.1 on 2018-10-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0003_auto_20181016_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
