# Generated by Django 2.1 on 2018-10-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0006_auto_20181018_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
