# Generated by Django 2.1 on 2018-10-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0007_produto_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='textinho',
            field=models.CharField(default='', max_length=150),
        ),
    ]
