# Generated by Django 2.1 on 2018-10-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0008_produto_textinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='link',
        ),
    ]
