# Generated by Django 2.1.2 on 2018-10-25 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0010_auto_20181025_0750'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Item do carrinho', 'verbose_name_plural': 'Itens do carrinho'},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart_key', 'produto')},
        ),
    ]
