# Generated by Django 2.1.2 on 2018-10-31 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=150)),
                ('subtitulo', models.CharField(max_length=150)),
                ('textinho', models.CharField(max_length=15000)),
                ('foto_cidade', models.ImageField(upload_to='images')),
                ('puzzle1', models.ImageField(upload_to='images')),
                ('puzzle2', models.ImageField(upload_to='images')),
                ('puzzle3', models.ImageField(upload_to='images')),
                ('puzzle4', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome'],
            },
        ),
    ]
